services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - backend-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - frontend-network
    volumes:
      - frontend_static:/app/static
    restart: no

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - backend-network
      - frontend-network
    volumes:
      - frontend_static:/app/static
    restart: always

volumes:
  frontend_static:
    
networks:
  backend-network:
    driver: bridge
    internal: true
  frontend-network:
    driver: bridge